/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.presentacion;

/**
 *
 * @author YENNYFER
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Director
     */
    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegistrarDirector = new javax.swing.JMenuItem();
        RegistrarEvaluador = new javax.swing.JMenuItem();
        RegistrarJefeDepartamento = new javax.swing.JMenuItem();
        RegistrarCoordinador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ListarAnteproyectos = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jMenu1.setText("Registrar ");

        RegistrarDirector.setText("Registrar Director");
        RegistrarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarDirectorActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarDirector);

        RegistrarEvaluador.setText("Registrar Evaluador");
        jMenu1.add(RegistrarEvaluador);

        RegistrarJefeDepartamento.setText("Registrar Jefe Departamento");
        jMenu1.add(RegistrarJefeDepartamento);

        RegistrarCoordinador.setText("Registrar Coordinador");
        jMenu1.add(RegistrarCoordinador);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar ");

        ListarAnteproyectos.setText("Listar Directores");
        ListarAnteproyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarAnteproyectosActionPerformed(evt);
            }
        });
        jMenu2.add(ListarAnteproyectos);

        jMenuItem5.setText("Listar Evaluadores");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Listar Jefe Departamento");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Listar Coordinadores");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarDirectorActionPerformed
       RegistrarDirector director  = new RegistrarDirector();
       escritorio.add(director);
       director.show();
    }//GEN-LAST:event_RegistrarDirectorActionPerformed

    private void ListarAnteproyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarAnteproyectosActionPerformed
       ListarFormatosTIA formato  = new ListarFormatosTIA();
       escritorio.add(formato);
       formato.show();
       
    }//GEN-LAST:event_ListarAnteproyectosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListarAnteproyectos;
    private javax.swing.JMenuItem RegistrarCoordinador;
    private javax.swing.JMenuItem RegistrarDirector;
    private javax.swing.JMenuItem RegistrarEvaluador;
    private javax.swing.JMenuItem RegistrarJefeDepartamento;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
