/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.presentacion;

import SGestionAnteproyectos.dto.FormatoTIC;
import SGestionAnteproyectos.sop_rmi.GestionAnteproyectosInt;
import cliente.utilidades.UtilidadesGenerales;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YENNYFER
 */
public class ListarFormatoTIC extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarFormatoTIC
     */
    private GestionAnteproyectosInt objGestionAnteproyectosInt;
    private UtilidadesGenerales utilidadesGenerales;
    private ArrayList<FormatoTIC> formatosTIC;
    private int idJefeDepto;
      
    public ListarFormatoTIC() {
        initComponents();
    }
       public ListarFormatoTIC(GestionAnteproyectosInt objGestionAnteproyectosInt, int idJefeDpto) throws  RemoteException{
           this.objGestionAnteproyectosInt = objGestionAnteproyectosInt;
           this.utilidadesGenerales = new UtilidadesGenerales();
           this.idJefeDepto = idJefeDpto;
           initComponents();

           formatosTIC = new ArrayList<>();
           inicializarTablaFormatosTIC();
           llenarTablaFormatosTIC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbAnteproyectos = new javax.swing.JTable();

        setTitle("Ateproyectos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1485476036-artboard-1_78544.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Lista de todos los anteproyectos");

        jtbAnteproyectos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtbAnteproyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbAnteproyectos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inicializarTablaFormatosTIC(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código Anteproyecto");
        model.addColumn("Estructura"); 
        model.addColumn("Concepto Dpto"); 
        model.addColumn("Observaciones");      
        this.jtbAnteproyectos.setModel(model);
    }
     private void llenarTablaFormatosTIC() {
        
         DefaultTableModel model = (DefaultTableModel) this.jtbAnteproyectos.getModel();
         utilidadesGenerales.limpiarTabla(jtbAnteproyectos);
         try {
             this.formatosTIC = objGestionAnteproyectosInt.consultarFormatosTIC();
         } catch (RemoteException ex) {
             Logger.getLogger(ListarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
         }
         if(!formatosTIC.isEmpty()){
         for (int i = 0; i < formatosTIC.size(); i++) {
             FormatoTIC objFormatoTIC = formatosTIC.get(i);
             if (objFormatoTIC.getIdJefeDeto() == idJefeDepto) {
                 String[] fila = {String.valueOf(objFormatoTIC.getCodigoAnteproyecto()), String.valueOf(objFormatoTIC.getEstructura()), String.valueOf(objFormatoTIC.getConceptoDepto()), objFormatoTIC.getObservaciones() + ""};
                 model.addRow(fila);
             }
         }
         }else{
           JOptionPane.showMessageDialog(null, "No ha Registrado formatos TIC", "Error", JOptionPane.ERROR_MESSAGE);       
         }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbAnteproyectos;
    // End of variables declaration//GEN-END:variables
}
