/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.presentacion;

import SGestionAnteproyectos.dto.FormatoTIA;
import SGestionAnteproyectos.sop_rmi.GestionAnteproyectosInt;
import cliente.utilidades.UtilidadesGenerales;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YENNYFER
 */
public class ListarFormtosAsigEvaluador extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarFormtosAsigEvaluador
     */
    private final GestionAnteproyectosInt objGestionAnteproyectosInt;
    private final int idEvaluador;
    private final UtilidadesGenerales utilidadesGenerales;
    private ArrayList<FormatoTIA> formatosTIAs;
    
    public ListarFormtosAsigEvaluador(GestionAnteproyectosInt objGestionAnteproyectos, int idEvaluador) throws  RemoteException{
        this.objGestionAnteproyectosInt = objGestionAnteproyectos;
        this.idEvaluador = idEvaluador;
        this.utilidadesGenerales = new UtilidadesGenerales();
        initComponents();
        inicializarTablaFormatosTIA();
        llenarTablaFormatosTIA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Formatos Asignados");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Formatos TIA Asignados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void inicializarTablaFormatosTIA(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo ");
        model.addColumn("Titulo");
        model.addColumn("Programa"); 
        model.addColumn("Estudiante 1");        
        model.addColumn("Estudiante 2"); 
         model.addColumn("Evaluador 1"); 
          model.addColumn("Evaluador 2"); 
        this.jTable1.setModel(model);
    }
 private void llenarTablaFormatosTIA() {
        
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        utilidadesGenerales.limpiarTabla(jTable1);
        try {
            this.formatosTIAs = objGestionAnteproyectosInt.consultarFormatosTIA();
        } catch (RemoteException ex) {
            Logger.getLogger(ListarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < formatosTIAs.size(); i++) {
            if (formatosTIAs.get(i).getIdentificacionEvaluador1() == idEvaluador || formatosTIAs.get(i).getIdentificacionEvaluador2() == idEvaluador) {
                FormatoTIA objFormatoTIA = formatosTIAs.get(i);
                String[] fila = {String.valueOf(objFormatoTIA.getCodigoAnteproyecto()), objFormatoTIA.getTituloAnteproyecto(), objFormatoTIA.getNombrePrograma(), objFormatoTIA.getNombreEstudiante1(), objFormatoTIA.getNombreEstudiante2(), String.valueOf(objFormatoTIA.getIdentificacionEvaluador1()), objFormatoTIA.getIdentificacionEvaluador2() + ""};
                model.addRow(fila);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
