/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.presentacion;

import SGestionAnteproyectos.dto.RolEnum;
import SGestionAnteproyectos.dto.Usuario;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosInt;
import javax.swing.table.DefaultTableModel;
import cliente.utilidades.UtilidadesGenerales;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author YENNYFER
 */
public class ListarUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarUsuarios
     */
    private GestionUsuariosInt objGestionUsuariosInt;
    private UtilidadesGenerales utilidadesGenerales;
    private ArrayList<Usuario> usuarios;
    
    public ListarUsuarios() {
        initComponents();
    }
    public ListarUsuarios(GestionUsuariosInt objGestionUsuariosInt) {
        this.objGestionUsuariosInt = objGestionUsuariosInt;
        this.utilidadesGenerales = new UtilidadesGenerales();
        this.usuarios = new ArrayList<>();
        initComponents();
        inicializarTablaUsuarios();
        llenarTablaUsuarios();
    }
private void inicializarTablaUsuarios(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Identificación ");
        model.addColumn("Nombre");
        model.addColumn("Rol"); 
        model.addColumn("Departamento");        
        model.addColumn("Usuario"); 
        model.addColumn("Contraseña"); 
        this.tblUsuarios.setModel(model);
    }
 private void llenarTablaUsuarios() {
        
    DefaultTableModel model = (DefaultTableModel)this.tblUsuarios.getModel();
    utilidadesGenerales.limpiarTabla(tblUsuarios);
    //this.usuarios.clear();
        try {
            this.usuarios = objGestionUsuariosInt.listarUsuarios();
        } catch (RemoteException ex) {
            Logger.getLogger(ListarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        for (int i = 0; i <usuarios.size(); i++) {
            Usuario objUsuario = usuarios.get(i);
            String[] fila = {String.valueOf(objUsuario.getId()),objUsuario.getNombre(),objUsuario.getRol().toString(),objUsuario.getDepartamento(),objUsuario.getUsuario(),objUsuario.getContrasena()+ ""};
            model.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();

        setBorder(null);
        setTitle("Usuarios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Lista de Usuario Registrados");

        tblUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModificar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            int fila = tblUsuarios.getSelectedRow();
            
            Usuario usuario = new Usuario();
            
            usuario.setId( Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString()));
            usuario.setNombre(tblUsuarios.getValueAt(fila, 1).toString());
            usuario.setRol(RolEnum.valueOf(tblUsuarios.getValueAt(fila, 2).toString()));
            usuario.setDepartamento(tblUsuarios.getValueAt(fila, 3).toString());
            usuario.setUsuario(tblUsuarios.getValueAt(fila, 4).toString());
            usuario.setContrasena(tblUsuarios.getValueAt(fila, 5).toString());
            
            objGestionUsuariosInt.actualizarUsuarios(usuario);
        } catch (RemoteException ex) {
            Logger.getLogger(ListarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
