/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.presentacion;

import SGestionAnteproyectos.dto.FormatoTID;
import SGestionAnteproyectos.sop_rmi.GestionAnteproyectosInt;
import SSeguimientoAnteproyectos.dto.Resolucion;
import SSeguimientoAnteproyectos.sop_rmi.SeguimientoAnteproyectosInt;
import cliente.utilidades.UtilidadesGenerales;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author YENNYFER
 */
public class RemitirResolucion extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemitirResolucion
     */
    private SeguimientoAnteproyectosInt objSeguimientoAnteproyectosInt;
    private GestionAnteproyectosInt objGestionAnteproyectosInt;
    private UtilidadesGenerales utilidadesGenerales;
    
    public RemitirResolucion() {
        initComponents();
    }
    public RemitirResolucion(SeguimientoAnteproyectosInt objSeguimientoAnteproyectosInt, GestionAnteproyectosInt objGestionAteproyectosInt) throws  RemoteException{
        this.objSeguimientoAnteproyectosInt = objSeguimientoAnteproyectosInt;
        this.objGestionAnteproyectosInt = objGestionAteproyectosInt;
        this.utilidadesGenerales = new UtilidadesGenerales();
        initComponents();
        jdtFechaRegistro.setDateFormatString("dd/MM/yyyy");
        consultarCodigosAnteproyectos();
        txtNumeroResolucion.setText(String.valueOf(objSeguimientoAnteproyectosInt.solicitarCodigoResolucion()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroResolucion = new javax.swing.JTextField();
        jdtFechaRegistro = new com.toedter.calendar.JDateChooser();
        btnRemitir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxCodigosAnteproyectos = new javax.swing.JComboBox<>();

        setBorder(null);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessregistration_signpen_negocio_inscripcio_2358.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Número de Resolución:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Registro:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Código del Anteproyecto:");

        txtNumeroResolucion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNumeroResolucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroResolucionKeyTyped(evt);
            }
        });

        jdtFechaRegistro.setDateFormatString("dd/MM/yyyy");
        jdtFechaRegistro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnRemitir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRemitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_send_128_28719.png"))); // NOI18N
        btnRemitir.setText("Remitir");
        btnRemitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemitirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Remitir Anteproyectos");

        cbxCodigosAnteproyectos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 181, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(194, 194, 194))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemitir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCodigosAnteproyectos, 0, 233, Short.MAX_VALUE)
                            .addComponent(jdtFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtNumeroResolucion))))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNumeroResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jdtFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxCodigosAnteproyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnRemitir)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemitirActionPerformed
       
        if (!txtNumeroResolucion.getText().isEmpty()) {
            if (!jdtFechaRegistro.toString().isEmpty()) {
                if (cbxCodigosAnteproyectos.getSelectedIndex() != -1) {
                    Resolucion resolucion = new Resolucion();
                    resolucion.setNumeroResolucion(Integer.parseInt(txtNumeroResolucion.getText()));
                    resolucion.setFechaRegistro(jdtFechaRegistro.getDate().toString());
                    resolucion.setCodigoAnteproyecto(Integer.parseInt(String.valueOf(cbxCodigosAnteproyectos.getSelectedItem())));
                    try {
                        if (!validarNumeroResulucion(Integer.parseInt(cbxCodigosAnteproyectos.getSelectedItem().toString()))) {
                            if (objSeguimientoAnteproyectosInt.almacenarResolucion(resolucion)) {
                                JOptionPane.showMessageDialog(null, "Anteproyecto Aprobado", "Información", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(null, "Resolución no remitida", "Advertencia", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "El número de resolución ya se encuentra Resgistrado", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        }
                    } catch (RemoteException ex) {
                        Logger.getLogger(RemitirResolucion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor Seleccione un valor Codigo Anteproyecto", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor Ingrese un valor para Fecha Registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese un valor para Número de Resolución", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemitirActionPerformed

    private void txtNumeroResolucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroResolucionKeyTyped
           utilidadesGenerales.verificarSoloNumeros(evt);
    }//GEN-LAST:event_txtNumeroResolucionKeyTyped
    private void consultarCodigosAnteproyectos() throws RemoteException {

        ArrayList<FormatoTID> objFormatoTIDs;
        objFormatoTIDs = objGestionAnteproyectosInt.consultarFormatosTID();

        if (!objFormatoTIDs.isEmpty()) {

            for (int i = 0; i < objFormatoTIDs.size(); i++) {
                if (objFormatoTIDs.get(i).getConceptoComite() == 1) {
                    cbxCodigosAnteproyectos.addItem(String.valueOf(objFormatoTIDs.get(i).getCodigoAnteproyecto()));
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se cuanta con Anteproyectos remitidos por el comite", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    
    private boolean validarNumeroResulucion(int numeroResolucion){
        
        try {
            if (objSeguimientoAnteproyectosInt.consultarNumerosResolucion(Integer.parseInt(txtNumeroResolucion.getText()))) {
                return true;
            }
        } catch (RemoteException ex) {
            Logger.getLogger(RemitirResolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemitir;
    private javax.swing.JComboBox<String> cbxCodigosAnteproyectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdtFechaRegistro;
    private javax.swing.JTextField txtNumeroResolucion;
    // End of variables declaration//GEN-END:variables
}
