/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;


import SGestionAnteproyectos.sop_rmi.GestionAnteproyectosInt;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosInt;
import SSeguimientoAnteproyectos.sop_rmi.SeguimientoAnteproyectosInt;
import SSeguimientoAnteproyectos.utilidades.UtilidadesRegistroS;
import cliente.presentacion.jfrIniciarSesion;
import cliente.sop_rmi.NotificacionImpl;
import cliente.utilidades.UtilidadesRegistroC;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author YENNYFER
 */
public class Conexion extends javax.swing.JFrame {

     private  GestionAnteproyectosInt objRemotoAnteproyectosInt;
     private GestionUsuariosInt objRemotoGestionUsuariosInt;
     private SeguimientoAnteproyectosInt objSeguimientoAnteproyectosInt;
     
     
    public Conexion() {
        setTitle("Registrar NS");
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConexion = new javax.swing.JPanel();
        lblDirIp = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        lblNumPuerto = new javax.swing.JLabel();
        txtNumPuerto = new javax.swing.JTextField();
        pnlBoton = new javax.swing.JPanel();
        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlConexion.setBackground(new java.awt.Color(0, 102, 153));
        pnlConexion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conexion Servidor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlConexion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pnlConexion.setLayout(new java.awt.GridLayout(5, 1));

        lblDirIp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDirIp.setForeground(new java.awt.Color(255, 255, 255));
        lblDirIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDirIp.setText("Cuál es el la dirección ip donde se encuentra  el n_s");
        pnlConexion.add(lblDirIp);

        txtIp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtIp.setText("localhost");
        pnlConexion.add(txtIp);

        lblNumPuerto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNumPuerto.setForeground(new java.awt.Color(255, 255, 255));
        lblNumPuerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumPuerto.setText("Cuál es el número de puerto por el cual escucha el n_s");
        pnlConexion.add(lblNumPuerto);

        txtNumPuerto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNumPuerto.setText("5000");
        pnlConexion.add(txtNumPuerto);

        pnlBoton.setLayout(new java.awt.GridBagLayout());

        btnConectar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socket.png"))); // NOI18N
        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        pnlBoton.add(btnConectar, new java.awt.GridBagConstraints());

        pnlConexion.add(pnlBoton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlConexion.getAccessibleContext().setAccessibleName("Conexión Servidor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
             
        String varIp = txtIp.getText();
        int varPuerto = Integer.parseInt(txtNumPuerto.getText());
        
        objRemotoGestionUsuariosInt = (GestionUsuariosInt) UtilidadesRegistroC.obtenerObjRemoto(varIp, varPuerto, "ObjetoRemotoUsuarios");

        objRemotoAnteproyectosInt = (GestionAnteproyectosInt) UtilidadesRegistroC.obtenerObjRemoto(varIp, varPuerto, "ObjetoRemotoAnteproyecto");

        objSeguimientoAnteproyectosInt = (SeguimientoAnteproyectosInt) UtilidadesRegistroC.obtenerObjRemoto(varIp, varPuerto, "ObjetoRemotoSeguimiento");

         try {
             NotificacionImpl objNotificacionImpl = new NotificacionImpl();
             objRemotoAnteproyectosInt.registrarCallback(objNotificacionImpl);
              //UtilidadesRegistroS.RegistrarObjetoRemoto(objNotificacionImpl, varIp, varPuerto, "ObjetoRemotoNotificacion");
    
         } catch (RemoteException ex) {
             Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        if (objRemotoAnteproyectosInt != null && objRemotoGestionUsuariosInt != null) {
            jfrIniciarSesion iniciarSesion = new jfrIniciarSesion(objRemotoGestionUsuariosInt, objRemotoAnteproyectosInt, objSeguimientoAnteproyectosInt);
            iniciarSesion.setVisible(true);
            this.dispose();
        } else {
            System.out.println("No se logra obtener el objeto remoto");
        }
    }//GEN-LAST:event_btnConectarActionPerformed
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Conexion().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JLabel lblDirIp;
    private javax.swing.JLabel lblNumPuerto;
    private javax.swing.JPanel pnlBoton;
    private javax.swing.JPanel pnlConexion;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtNumPuerto;
    // End of variables declaration//GEN-END:variables
}
